### ISSUE TITLE
Model 218 Temperature Monitor

### ISSUE THREAD

**Issue by labrador208** [lakeshorecryotronics/python-driver#2]
Hi,

Are there any plans or sample code available for use on a Model 218 Temperature monitor?

**Comment by Noah-Lake-Shore-Cryotronics** [comment]
Unfortunately, we aren't planning to extend the python driver to specifically handle any of our instruments that don't have USB or Ethernet connections. 

If you would like some help connecting and communicating with the 218 using python, the Lake Shore Cryotronics forum would be a good place to ask the question. Our support team actively monitors the forum for requests for assistance. https://forums.lakeshore.com/board/91/temperature-controllers-monitors
