### ISSUE TITLE
Lakeshore Temperature Controller 325 issure

### ISSUE THREAD

**Issue by manimar2070** [lakeshorecryotronics/python-driver#3]
Hi,
I've pip installed the Lakeshore python code but the Lakeshore model is a Temperature controller 325 that when I use the blow command it returns error:

from lakeshore import Model325
my_instrument = Model325()
print(my_instrument.query('*IDN?'))

ImportError Traceback (most recent call last)
in
----> 1 from lakeshore import Model325
2 my_instrument = Model325()
3 print(my_instrument.query('*IDN?'))

ImportError: cannot import name 'Model325' from 'lakeshore' (C:\Users\mrahman9\Anaconda3\lib\site-packages\lakeshore_init_.py)

I understand the error that says the model is not supported but can I ask why?
I've seen the model 335 is included in the documents but not 325.
I'm wondering if there is any way to get the 325 connected to my laptop and using this amazing Lakeshore python code.
I appreciate your assistance.
Best,
Mary

**Comment by Noah-Lake-Shore-Cryotronics** [comment]
Hi Mary, my apologies for the very delayed response. Unfortunately, we aren't planning to extend the python driver to specifically handle any of our instruments that don't have USB or Ethernet connections.

If you would like some help connecting and communicating with the 325 using python, the Lake Shore Cryotronics forum would be a good place to ask the question. Our support team actively monitors the forum for requests for assistance. [https://forums.lakeshore.com/board/91/temperature-controllers-monitors](https://forums.lakeshore.com/board/91/temperature-controllers-monitors)

**Comment by manimar2070** [comment]
Thanks Noah for the reply. Will check the forum by sure.
Best,
Mary
