### ISSUE TITLE
Is there a way to get AC readings from the F71 teslameter with the current available functions in teslameter.py?

### ISSUE THREAD

**Issue by leboVegitaJA17** [lakeshorecryotronics/python-driver#7]
The sample code provided here: https://lake-shore-python-driver.readthedocs.io/en/latest/teslameter.html configures the meter to be DC mode: 'SENSE:MODE DC'. And the configurations within the F71 teslameter.py python file configure the meter to fetch DC data from the buffer: FETC:BUFF:DC. Is there a command or method I am missing to get X, Y, and Z readings in AC? 

To specify, the def stream_buffered_data(self, length_of_time_in_seconds, sample_rate_in_ms) rely on FETC:BUFF:DC queries on line 133 and 136. Can this be changed to FETC:BUFF:AC? And it seems like the other two buffer functions:

get_buffered_data_points(self, length_of_time_in_seconds, sample_rate_in_ms) 
and
def log_buffered_data_to_file(self, length_of_time_in_seconds, sample_rate_in_ms, file)

rely on the stream_buffered_data, and therefore relying on DC buffer data.

Similarly, there is no AC equivalent of these two functions.  
 def get_dc_field(self):
        """Returns the DC field reading."""
        return float(self.query("FETCH:DC?"))

    def get_dc_field_xyz(self):
        """Returns the DC field reading."""

Please let me know if there is a way to stream X, Y, Z AC readings into the meter. 

Thanks,

Nick

**Comment by leboVegitaJA17** [comment]
Thanks for your response. Though the code runs, it returns two readings. If I print(rms_xyz_sample) inside the loop, I get output like the following.

(3.13362359959963e-06, 3.13362359959963e-06, 0.0, 0.0)
(3.06724911470743e-06, 3.06724911470743e-06, 0.0, 0.0)
(3.15267761893626e-06, 3.15267761893626e-06, 0.0, 0.0)
(3.09777851889376e-06, 3.09777851889376e-06, 0.0, 0.0)
(3.05340312501872e-06, 3.05340312501872e-06, 0.0, 0.0)

I'm not sure what the second element of rms_xyz_tuple represents considering I have a single axis transverse probe. They seem to be the same value but I'd like to check that there is not something wrong. Here is the information about my probe:

>>> probe_info = my_teslameter.get_probe_information()
>>> print(probe_info)
{'model_number': '"FP-2X-250-TS15"', 'serial_number': '"(I removed identifying info)"', 'probe_type': '"Standard"', 'sensor_type': '"2Dex"', 'sensor_orientation': '"TRANSVERSE"', 'number_of_axes': '1', 'calibration_date': '"8-1-2018"'}

**Comment by Noah-Lake-Shore-Cryotronics** [comment]
I see nothing wrong with that result. Apologies my previous response wasn't quite accurate. The get_rms_xyz function returns a tuple of four values. The magnitude RMS reading, the x axis RMS reading, the y axis RMS reading, and the z axis RMS reading. Since you are using a single axis probe you are only getting a measurement for the magnitude reading and the x axis reading. In the case of a single axis probe the magnitude reading is the same as the x reading.

For your case I would revise the example script like so:

```

from lakeshore import Teslameter
from time import sleep

NUMBER_OF_RMS_SAMPLES = 100
AVERAGING_TIME_IN_SECONDS = 1

# Connect to the first available Teslameter over USB
my_teslameter = Teslameter()

# Configure the field measurement mode to AC and the averaging time in number of 10 ms samples
my_teslameter.configure_field_measurement_setup("AC", averaging_samples=(AVERAGING_TIME_IN_SECONDS * 100))

# Create a file to write data into.
data_file = open("teslameter_rms_data.csv", "w")
# Write a header labeling the three columns
data_file.write('rms x,rms y,rms z\n')

# Repeatedly query the instrument and write the results to a file, waiting for the averaging time between each query
for n in range(0, NUMBER_OF_RMS_SAMPLES):
    sleep(AVERAGING_TIME_IN_SECONDS)
    rms_sample = my_teslameter.get_rms_field()
    # Separate the three values into a CSV format
    data_file.write(f'{rms_sample}\n')

data_file.close()

```

I recommend taking a look at the [product manual](https://www.lakeshore.com/docs/default-source/product-downloads/manuals/f41_f71manual.pdf) for more information about the instrument's capabilities:
